### ISSUE TITLE
Dashboard Not Showing Sites

### ISSUE THREAD

**Issue by mwweb** [joomlatools/joomlatools-vagrant#99] opened 2017-09-21 07:33 UTC
All my box instances that I have installed were updated to Joomla 3.8.0, and they no longer show in the dashboard. Is there something that I need to do on Joomla in a Box, or does something need to be updated?

**Comment by stevenrombauts** [comment] 2017-09-21 08:37
Hi @mwweb, we noticed this issue too. The problem is in the `/home/vagrant/scripts/dashboard/index.php` file, which fails to find the version class for Joomla 3.8 so excludes it from the list. We'll have to look for a fix.

If you have any idea how to solve this, we always welcome a pull request :)

**Comment by mwweb** [comment] 2017-09-21 17:16
OK. It looks like in /home/vagrant/scripts/dashboard/index.php, a change needs to be made starting at line 30.

In pre-3.8, the version was in libraries/cms/version/version.php.

In 3.8.0 the Joomla! devs moved the file to libraries/src/Version.php.

The version infromation is stored in final class Version instead of final class JVersion.

**Comment by stevenrombauts** [comment] 2017-09-21 17:19
Thanks for looking further into this @mwweb! I just pushed a fix that should display these sites again. 

If you want to try it out on your end too you can copy [the highlighted text](https://github.com/joomlatools/joomlatools-vagrant/blob/5a9c9c1992fb85fbdb76914c13325d4fe7ef34d5/puppet/modules/custom/profiles/files/box/scripts/dashboard/index.php#L30-L71) from index.php to your box copy to make it work.

**Comment by mwweb** [comment] 2017-09-21 17:23
That did it.

**Comment by stevenrombauts** [comment] 2017-09-22 11:05
Great, thanks again for your help @mwweb! This change will be included in the next release.

**Closed by stevenrombauts** 2017-09-22 11:05 UTC
Labels: bug
