### ISSUE TITLE
Move dashboard and box to a separate repo

### ISSUE THREAD

**Issue by stevenrombauts** [joomlatools/joomlatools-vagrant#114] opened 2017-11-14 23:03 UTC
Move the dashboard and box to a separate repository so we can have them updated separately from the box. Use the existing auto-update script for console to check for new versions. Also add GA to the dashboard.

**Comment by yiendos** [comment] 2020-10-20 08:28
## Marking as invalid

Possibly duplicate of another piece of work, dashboard and support are completely independent repos, and have their own tests as well.

**Closed** 2020-10-21 08:27 UTC
Labels: feature, invalid
