### ISSUE TITLE
Configurable mount options

### ISSUE THREAD

**Issue by tomjanssens** [joomlatools/joomlatools-vagrant#54] opened 2016-04-15 09:51 UTC
Make it possible to add mount_options to config.shared.yml.

See: https://github.com/mitchellh/vagrant/blob/master/website/docs/source/v2/synced-folders/nfs.html.md

**Comment by stevenrombauts** [comment] 2018-01-10 10:53
Closing, duplicate of #77.

**Closed by stevenrombauts** 2018-01-10 10:53 UTC
