### ISSUE TITLE
Incorrect permissions over /home/vagrant/.config

### ISSUE THREAD

**Issue by yiendos** [joomlatools/joomlatools-vagrant#148] opened 2019-06-05 08:58 UTC
Seems we have incorrect permissions over a home folder:
`/home/vagrant/.config/` 

Consequently git related activities gives rise to an error:
```
$ git pull --rebase
warning: unable to access '/home/vagrant/.config/git/attributes': Permission denied
Already up to date.
```

Whilst the git actions do succeed we should look to chown -R the permissions to `vagrant:vagrant` to be in keeping with other permissions for this folder. Currently they are set to `root:root`

<img width="1141" alt="Screenshot 2019-06-05 at 09 54 48" src="https://user-images.githubusercontent.com/3769817/58943741-4ed64000-8778-11e9-8634-eb9d82a3a269.png">

**Comment by stevenrombauts** [comment] 2019-06-05 12:03
@yiendos Is this on a new build? This directory can only be set to root if it was created by some process that ran as root which we should be able to solve by finding the responsible `exec` resource in the Puppet code.

**Comment by yiendos** [comment] 2019-06-05 14:44
@stevenrombauts going by the contents of the folder in question:
```
$ tree -L 3 ~/.config/configstore
/home/vagrant/.config/configstore
└── update-notifier-npm.json
``` 

I'd say it's something npm related:
https://www.npmjs.com/package/update-notifier

But not much of clue when this get installed to the box?

**Comment by stevenrombauts** [comment] 2019-06-06 13:05
@yiendos I think it might have something to do with the installation of CloudCommander:  https://github.com/joomlatools/joomlatools-vagrant/blob/master/puppet/environments/box/modules/profiles/manifests/cloudcommander.pp#L6-L11

This runs as root but explicitly sets the home directory to /home/vagrant. Running this as the vagrant user might solve it.

**Comment by yiendos** [comment] 2019-06-06 15:36
@stevenrombauts Absolutely spot on with that one, indeed it was cloud commander that was creating these folders. 

We can certainly set the group no problems, but changing the user from which the exec will run (and therefore ultimate owner):
```
==> default: Notice: /Stage[main]/Profiles::Cloudcommander/Exec[npm-install-cloudcommander]/returns: 
==> default: Notice: /Stage[main]/Profiles::Cloudcommander/Exec[npm-install-cloudcommander]/returns: npm ERR! A complete log of this run can be found in:
==> default: Notice: /Stage[main]/Profiles::Cloudcommander/Exec[npm-install-cloudcommander]/returns: npm ERR!     /home/vagrant/.npm/_logs/2019-06-06T14_51_46_970Z-debug.log
==> default: Error: 'npm install cloudcmd@11.8.5 -g' returned 243 instead of one of [0]
==> default: Error: /Stage[main]/Profiles::Cloudcommander/Exec[npm-install-cloudcommander]/returns: change from 'notrun' to ['0'] failed: 'npm install cloudcmd@11.8.5 -g' returned 243 instead of one of [0]
```

Output of this log:
```
/home/vagrant/.npm/_logs/2019-06-06T14_51_46_970Z-debug.log

1102 error If you believe this might be a permissions issue, please double-check the
1102 error permissions of the file and its containing directories, or try running
1102 error the command again as root/Administrator (though this is not recommended).
1103 verbose exit [ -13, true ]
``` 

So we can't install npm stuff without being root, which is pretty standard fare. However what we can do however is nip in there first and create the directory with the correct owner and group before npm is even called. 

Seems that $HOME/.config is a pretty standard place for configs.

**Comment by stevenrombauts** [comment] 2019-06-20 14:30
@yiendos Thanks for testing this. It makes sense because we're installing it globally (`-g`) flag, so npm needs administrative rights. We are also _running_ the process itself as root but this is not creating the `.config` directory (because we don't change home directory in the [systemd unit file](https://github.com/joomlatools/joomlatools-vagrant/blob/master/puppet/environments/box/modules/profiles/files/cloudcommander/systemd.service))

I'm updating the global Node set up in #138 so let's finish that first and get back to this? Either we install it locally as the `vagrant` user and use the correct path in the [systemd unit](https://github.com/joomlatools/joomlatools-vagrant/blob/master/puppet/environments/box/modules/profiles/files/cloudcommander/systemd.service#L7) or stop installing with the `HOME=/home/vagrant` env var, which is the cause of our troubles here.

**Comment by stevenrombauts** [comment] 2019-06-26 15:02
@yiendos  Node has been upgraded in #138 and reinstalling cloudcmd didn't give me any trouble (have yet to try a new build from scratch)

**Comment by stevenrombauts** [comment] 2019-11-19 17:05
Marking as closed.

**Closed by stevenrombauts** 2019-11-19 17:05 UTC
Labels: bug
